# This is a basic workflow to help you get started with Actions

name: Imprime Data

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    name: job 1
    runs-on: ubuntu-latest
    
    steps:
      - name: data 1
        run: date
        
  job2:
    name: job 2
    runs-on: windows-latest
      
    steps:
      - name: data 2
        run: date
        
  job3: 
    name: job 3
    runs-on: macos-latest
    
    steps:
      - name: data 3
        run: date
        
  job4:
    name: job 4
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    
    steps: 
      - name: data 4
        run: date
        
